### ISSUE TITLE
메뉴 애니메이션 조정

### ISSUE THREAD

**Issue by jisungbin** [nolbo/kakaotalkbot-docs#10]
<img src="https://user-images.githubusercontent.com/40740128/134457876-ef3680c8-010d-414d-b375-7c817c9e1aef.png" width="33%" />
메뉴 부분에 애니메이션이 너무 오랫동안 진행돼, 사용자 편의성을 저하시킵니다. @nolbo  <br/>
한국인이라 빠른걸 좋아하는데, 메뉴-카테고리 모두 로드되기까지 애니메이션이 너무 깁니다.
애니메이션을 없애거나, 시간 조정이 필요해 보입니다.

**Comment by nolbo** [comment]
시간날때 수정해보겠습니다

근데 새 문서 완성되면 사라지는ㄷ
