### ISSUE TITLE
카테고리가 보이지 않음

### ISSUE THREAD

**Issue by jisungbin** [nolbo/kakaotalkbot-docs#11]
<img width="33%" alt="스크린샷 2021-09-23 오후 2 20 37" src="https://user-images.githubusercontent.com/40740128/134458112-406b4c37-fe9f-446a-8a69-89c590edb3bf.png">
메뉴 부분에서 가끔씩 카테고리가 로드되지 않습니다. @nolbo

**Comment by nolbo** [comment]
그것도 애니메이션에 의해 발생한 버그입니다
애니메이션을 없애서 해결하겠습니다
