### ISSUE TITLE
도움주신 분들 추가

### ISSUE THREAD

**Issue by jisungbin** [nolbo/kakaotalkbot-docs#12]
저번에 `savedInstanceState`  부분에 대해 도움을 드렸는데 저도 [도움주신 분들](https://kkotbot-docs.kro.kr/appendix.html)에 추가가 가능할까요? @nolbo

**Comment by nolbo** [comment]
새 문서에다가 도움주신 분들에 추가하겠습니다.
(새 문서에서는 '도움주신 분들'이 '기여자'로 변경될 예정입니다.)
