### ISSUE TITLE
개발 여부

### ISSUE THREAD

**Issue by jisungbin** [nolbo/kakaotalkbot-docs#13]
현재 개발이 진행되고 있나요? @nolbo

**Comment by nolbo** [comment]
기숙사에 갇혀있습니다..

**Comment by jisungbin** [comment]
@nolbo 노트북 없으신가요?!

**Comment by nolbo** [comment]
어허 그런거 못들고갑니다

공부할 사람만 뽑아서 넣는 곳인데

**Comment by franknoh** [comment]
> 어허 그런거 못들고갑니다
> 
> 공부할 사람만 뽑아서 넣는 곳인데

:thinking: @nolbo 유지보수 제가 할까요

**Comment by jisungbin** [comment]
> 어허 그런거 못들고갑니다
> 
> 공부할 사람만 뽑아서 넣는 곳인데

@nolbo 좋은 학교 가셨나 보네용 ㄷㄷ 응원합니다!
