### ISSUE TITLE
코드 스타일

### ISSUE THREAD

**Issue by jisungbin** [nolbo/kakaotalkbot-docs#14]
![image](https://user-images.githubusercontent.com/40740128/141676740-d3e83b76-cbee-49b7-b27a-61f014706dd0.png)

위 사진 외에 다른 부분들을 포함해서 코드 스타일을 표준 스타일 가이드로 통일해야 할 거 같습니다.

**Comment by jisungbin** [comment]
@nolbo

**Comment by nolbo** [comment]
알겠습니다

근데 왜 없어질 문서에만 pr을...

**Comment by jisungbin** [comment]
> 알겠습니다
> 
> 근데 왜 없어질 문서에만 pr을...

참고로 `pr` 와 `issue` 는 다릅니다.
